# Generated by Django 5.1.1 on 2025-04-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0010_alter_userprofile_cafe_name_and_more'),
        ('promotions', '0003_event_eventtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='authentication_app.userprofile'),
        ),
    ]
