# Generated by Django 5.1.1 on 2025-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='thread_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
