# Generated by Django 5.1.1 on 2025-01-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_usersmodel_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
    ]
