# Generated by Django 5.1.1 on 2025-01-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_usersmodel_chat_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='chat_history',
        ),
    ]
