# Generated by Django 5.1.1 on 2025-01-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_usersmodel_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
