# Generated by Django 5.1.1 on 2025-02-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_usersmodel_created_at_and_more'),
        ('users_app', '0005_alter_usersmodel_id'),
    ]

    operations = [
    ]
