services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn GP.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: GP.settings
    staticPublishPaths:
      - source: staticfiles
        path: /static
      - source: media
        path: /media
