# Generated by Django 5.1.1 on 2025-01-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontranslation',
            name='question_ar',
        ),
    ]
