# Generated by Django 5.1.6 on 2025-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0008_alter_userprofile_cafe_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/'),
        ),
    ]
