# Generated by Django 5.1.6 on 2025-03-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0009_alter_userprofile_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cafe_name',
            field=models.CharField(default='cafe', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_file',
            field=models.FileField(default='-', upload_to='static/uploads/'),
            preserve_default=False,
        ),
    ]
