# Generated by Django 5.1.6 on 2025-04-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication_app", "0010_alter_userprofile_cafe_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
