# Generated by Django 5.1.6 on 2025-03-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('قيد الانتظار', 'قيد الانتظار'), ('مقبول', 'مقبول'), ('مرفوض', 'مرفوض')], default='قيد الانتظار', max_length=15),
        ),
    ]
