# Generated by Django 5.1.6 on 2025-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cafe_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cafe_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Filler', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
