# Generated by Django 5.1.6 on 2025-03-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='authentication_app.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='authentication_app.city'),
            preserve_default=False,
        ),
    ]
