# Generated by Django 5.1.6 on 2025-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_area_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cafe_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/logos/'),
        ),
    ]
