# Generated by Django 5.1.6 on 2025-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userprofile_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='thread_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cafe_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
