# Generated by Django 5.1.6 on 2025-04-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_remove_userprofile_thread_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="area",
            table="authentication_area",
        ),
        migrations.AlterModelTable(
            name="city",
            table="authentication_city",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="authentication_userprofile",
        ),
    ]
