# Generated by Django 5.1.1 on 2025-01-18 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GP_app', '0002_usersmodel_delete_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersModel',
        ),
    ]
